WIP Install Flyvemdm and Fusioninventory plugins
flyve-mdm/docker-environment pull request #24
Opened 2018-06-15 22:42 UTC by ingluife

Hi, @flyve-mdm/backend-development.

In this changes i configured  the cloning process of Flyvemdm and Fusioninventory. This process is executed after the GLPI's instalation process and starting automatically.
For that i add the environment variables necesary for the cloning. Also i configure a container additional for Mosquitto service required by Flyvemdm.

For Mosquitto service i will have configure and compile the auth-plugin.

The mosquitto's container is based in the Docker official image in:
https://hub.docker.com/_/eclipse-mosquitto/ 

### References
#21

Closes #23

2018-06-16 21:21 UTC, DIOHz0r requested changes

2018-06-16 21:21 UTC, DIOHz0r commented on .env
> +GLPI_PLUGINS_DIRECTORY=/plugins
There is no need to set a plugin directory var because it'll be always the plugin directory inside GLPI home path, please remove/adjust that on the rest of the code

2018-06-16 21:21 UTC, DIOHz0r commented on docker/php/cliinstall.sh
> +    su - www-data -c 'composer install --no-dev'
we must install develop vendors for Flyvemdm

2018-06-16 21:21 UTC, DIOHz0r commented on docker/php/cliinstall.sh
> +    cd $HOMEPATH$GLPI_PLUGINS_DIRECTORY$FLYVEMDM_PATH
I think this is not necessary if you remove the else statement and simplify the if block to only print the message.

2018-06-18 19:04 UTC, ingluife commented on .env
> +GLPI_PLUGINS_DIRECTORY=/plugins
Ok, i will change it

2018-06-18 19:04 UTC, ingluife commented on docker/php/cliinstall.sh
> +    su - www-data -c 'composer install --no-dev'
That's right.

2018-06-18 19:11 UTC, ingluife commented on docker/php/cliinstall.sh
> +    cd $HOMEPATH$GLPI_PLUGINS_DIRECTORY$FLYVEMDM_PATH
Ok, i will do it.

2018-06-18 22:46 UTC, ingluife commented
Hi, @flyve-mdm/backend-development.

This is ready for Test in LINUX and MAC.

2018-06-19 12:34 UTC, ajsb85 approved these changes

2018-06-19 12:39 UTC, DIOHz0r approved these changes

2018-06-19 12:39 UTC, merged