WIP Add documentation articles
flyve-mdm/docker-environment pull request #34
Opened 2018-07-13 21:50 UTC by Naylin15

### Changes description
Add the documentation articles following the HackMD provided by @ingluife 

https://hackmd.io/cESB4-AARAWKI1JdGk0lUQ?both

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |1|

### References

Closes #8 
Related #3 
Depends on #N/A

2018-07-13 22:00 UTC, ajsb85 approved these changes

2018-07-14 00:14 UTC, ajsb85 approved these changes

2018-07-16 21:16 UTC, ajsb85 approved these changes

2018-07-18 16:15 UTC, Naylin15 commented
The documentation is finished, I'm having a small issue with the css for the tables, not taking the zebra style

![captura de pantalla 2018-07-18 a la s 12 14 34 p m](https://user-images.githubusercontent.com/30867977/42894164-2f1aca98-8a84-11e8-9dfd-1e6f66a41012.png)

2018-07-18 16:25 UTC, ajsb85 approved these changes

2018-07-18 19:55 UTC, Naylin15 commented
The issue with the zebra style is with browser Chrome in Firefox it displays the style correctly
![captura de pantalla 2018-07-18 a la s 3 54 54 p m](https://user-images.githubusercontent.com/30867977/42904399-f698b60c-8aa2-11e8-879e-2d00d316a4bf.png)

2018-07-18 20:40 UTC, ingluife approved these changes

2018-07-18 21:43 UTC, Naylin15 commented
Issue style solved, it was caused by cache

2018-07-18 22:45 UTC, ingluife requested changes

2018-07-18 22:45 UTC, ingluife commented on _posts/static/2018-07-16-installation-pl.md
> +To start with the installation process, we must get the [Flyve MDM Docker Environment](https://github.com/flyve-mdm/docker-image) from its source.
Hi, @Naylin15. 

In this line, we must update the repository source to:

> https://github.com/flyve-mdm/docker-environment

2018-07-18 22:45 UTC, ingluife commented on _posts/static/2018-07-16-installation-pl.md
> +- Using git, clone the repo: ```git clone https://github.com/flyve-mdm/docker-image.git```
The same here.

2018-07-18 22:45 UTC, ingluife commented on _posts/static/2018-07-16-installation-pl.md
> +- [From GitHub Releases](https://github.com/flyve-mdm/docker-image/releases)
The same here.

2018-07-19 13:51 UTC, ingluife approved these changes

2018-07-19 13:52 UTC, merged